### ISSUE TITLE
Mouse does not work in macos 10.0 - solution provided

### ISSUE THREAD

**Issue by anonymousaga** [adespoton/utmconfigs#10]
Due to a recent [bug](https://github.com/utmapp/UTM/issues/3504) in UTM, via=cuda fails to actually use cuda, and the mouse/keybiard in Mac OS X 10.0 fails to work. A quick & easy fix is going to the VM settings, clicking thr "QEMU" tab, scrolling to the bottom, and adding the line `-machine mac99,via=cuda,usb=off` as a custom config entry. This overrides the first (bugged) machine config and makes the VM work, regardless of this bug

**Comment by adespoton** [comment]
This was a bug from UTM 4.0 to 4.0.9 and is fixed in 4.1.0.-Em On Nov 27, 2022, at 10:03 AM, Anonymous ***@***.***> wrote:﻿
Due to a bug in UTM, via=cuda fails to actually use cuda, and the mouse/keybiard in Mac OS X 10.0 fails to work. A quick & easy fix is going to the VM settings, clicking thr "QEMU" tab, scrolling to the bottom, and adding the line -machine mac99,via=cuda,usb=off as a custom config entry. This overrides the first (bugged) machine config and makes the VM work, regardless of this bug

**Comment by anonymousaga** [comment]
@adespoton 4.10 is still in beta, so many people might not be using it yet

**Comment by N1-TR0** [comment]
<img width="912" alt="image" src="https://github.com/adespoton/utmconfigs/assets/66451996/8829b7dd-c584-4d24-8d59-114eb53406fb">
