### ISSUE TITLE
Open GL not available?

### ISSUE THREAD

**Issue by roto31** [adespoton/utmconfigs#28]
Hello!
First off, great compilation of configurations for getting the multiple versions of Classic MacOS and Mac OS X to run on UTM. Being able to do so is great on Apple Silicon. 

I have Lion 10.7.5 setup on my MacStudio with the intention of being able to play some of my vintage games. One of them, SPORE, requires Open GL and when attempting to start the game I get the error "Video Acceleration Required - Video hardware acceleration is currently disabled due to safe mode operation or a driver error. Please ensure you have a working OpenGL Hardware Renderer and try again." 

Is this a limitation of the configuration built to run MacOS 10.7.5 Lion or UTM? If it is a simple fox, how do I tweak the configuration to get OpenGL acceleration?

Under System Profiler it is showing a Generic GPU with 3MB of VRAM and Kernel Extension Info is showing "No Kext Loaded"

Thank you!

**Comment by adespoton** [comment]
Open GL depends on hardware acceleration.  QEMU-X86_64 doesn’t emulate a graphics card; everything is done via CPU.  So, no graphics acceleration.So sadly, there’s still no way to run 32-bit software with graphics acceleration on Apple Silicon (unless Parallels figured that out).-Em On Mar 24, 2024, at 7:58 AM, roto31 ***@***.***> wrote:﻿
Hello!
First off, great compilation of configurations for getting the multiple versions of Classic MacOS and Mac OS X to run on UTM. Being able to do so is great on Apple Silicon.
I have Lion 10.7.5 setup on my MacStudio with the intention of being able to play some of my vintage games. One of them, SPORE, requires Open GL and when attempting to start the game I get the error "Video Acceleration Required - Video hardware acceleration is currently disabled due to safe mode operation or a driver error. Please ensure you have a working OpenGL Hardware Renderer and try again."
Is this a limitation of the configuration built to run MacOS 10.7.5 Lion or UTM? If it is a simple fox, how do I tweak the configuration to get OpenGL acceleration?
Thank you!
