### ISSUE TITLE
Update config.plist for 10.2 Configuration

### ISSUE THREAD

**Issue by garamb1** [adespoton/utmconfigs#31]
Hi! I was trying out the configuration for 10.2 and I noticed, when imported, that the `snapshot` argument is present inside the configuration and needs to be removed in order to retain the changes to the VM (especially the HD image) after a reboot.

For reference, config.plist should be updated from:
```
[...]
		<key>AddArgs</key>
		<array>
			<string>-g 1280x720x32</string>
			<string>-usbdevice tablet</string>
			<string>-snapshot</string>
		</array>
[...]
```

To:
```
[...]
		<key>AddArgs</key>
		<array>
			<string>-g 1280x720x32</string>
			<string>-usbdevice tablet</string>
		</array>
[...]
```

Happy to put a PR if needed. Thank you!

**Comment by adespoton** [comment]
Whoops! I hadn’t realized that snuck in to the published version.  Please PR, and I’ll accept.-Em On May 3, 2024, at 11:08 AM, Vincenzo ***@***.***> wrote:﻿
Hi! I was trying out the configuration for 10.2 and I noticed, when imported, that the snapshot argument is present inside the configuration and needs to be removed in order to retain the changes to the VM (especially the HD image) after a reboot.
For reference, config.plist should be updated from:
[...]
		<key>AddArgs</key>
		<array>
			<string>-g 1280x720x32</string>
			<string>-usbdevice tablet</string>
			<string>-snapshot</string>
		</array>
[...]

To:
[...]
		<key>AddArgs</key>
		<array>
			<string>-g 1280x720x32</string>
			<string>-usbdevice tablet</string>
		</array>
[...]

Happy to put a PR if needed. Thank you!
