### ISSUE TITLE
Mac OS 7.6.1 SCSI drive incorrect disk size

### ISSUE THREAD

**Issue by kinless** [adespoton/utmconfigs#41]
I tried using the config for the Mac OS 7.6.1 guest in the latest UTM (4.6.3) on macOS 15.

The CD image boots fine, but the pre-formatted Macintosh HD is only 18.6MB in size which is not enough for any kind of installation. I've attempted to reformat using the CD's Apple HD SC Setup app, as well as spinning up a new SCSI image and reformatting that one, but it always falls back to 18.6MB of formatted space no matter what size is chosen.

![not-enough-space](https://github.com/user-attachments/assets/b7fca4d6-cc91-4140-8382-c40a1c8cca96)

**Comment by adespoton** [comment]
Odd; not sure what happened—I’ll try to get it swapped out for a 1GB formatted partition.  They’re cloned, so that probably affected all the configurations.-Em On Dec 20, 2024, at 9:42 PM, Joey Kincer ***@***.***> wrote:﻿
I tried using the config for the Mac OS 7.6.1 guest in the latest UTM (4.6.3) on macOS 15.
The CD boots fine, but the pre-formatted Macintosh HD is only 18.6MB in size which is not enough for any kind of installation. I've attempted to reformat using the CD's Apple HD SC Setup app, as well as spinning up a new SCSI image and reformatting that one, but it always falls back to 18.6MB of formatted space no matter what size is chosen.
not-enough-space.png (view on web)

**Comment by kinless** [comment]
Thanks. I'm not sure if it's the partition. I deleted the one in there, spun up a new SCSI device and formatted it using HD SC Setup, but the new partition still shows 18.6MB. I only have surface-level knowledge of QEMU configurations and wouldn't know if it was something else causing the incorrect format size, the boot CD itself is flawed, or recent updates to UTM or QEMU causing an issue?

**Comment by adespoton** [comment]
Seems to be something to do with the UTM config of QEMU; I don't have this issue with vanilla QEMU, but even with uncompressed images, UTM is formatting them as 18.6MB.  I'll stick in an actual 1GB-partitioned drive instead, pre-formatted outside the current UTM.

**Comment by adespoton** [comment]
Aha!  Not sure why, but Apple HD SC Setup was creating a default 18.6MB partition; going back in and checking the partitions shows the volume itself is 1GB.  I've replaced the small partition one with one that uses the entire volume, and it works great.  I'll update the configs shortly.

**Comment by adespoton** [comment]
Config files updated with properly partitioned images.

**Comment by kinless** [comment]
@adespoton thank you sir, that worked a treat! Successfully installed 7.6.1. Get to relive my high school days with this OS lol
